Mining tools for BEC
====================

## Patch for Parity

This patch will prepare your Parity instance to automatically add BEC Claim() transaction into a block mined by your
node.

Features:

* add BEC claim transaction into mined blocks (before mining)
* doesn't send such transaction to the network without including it into mined block
* you receive all ETC spent on gas back (because you're miner of that block)

Note:

* you have to unlock that account for mining node, and put small amount of Ether into that wallet
* it can be any wallet address, and it's recommended to use a separate addresses for mining coinbase and BEC claim

### Prepare Environment

**Note**: you have to compile Parity using same OS that you'll use for mining. If it's going to be a Linux then compile binaries on
linux machine too.

Install Rust compiler from https://www.rustup.rs/:
----
curl https://sh.rustup.rs -sSf | sh
----

Get Parity sources:
----
git clone git@github.com:ethcore/parity.git
cd parity
git checkout v1.4.10
----

### Apply patch

Copy `parity-1.4.10.path` in that dir and apply it to parity sources:

----
curl https://raw.githubusercontent.com/splix/bec/master/miner/parity-1.4.10.patch > parity-1.4.10.patch
git apply parity-1.4.10.patch
----

### Compile Parity

----
cargo build --release
----

Wait 20-30 minutes to get Parity compiled, and finally you'll have a Parity with BEC mining built in, get it
at `./target/release/parity`

You have to run Parity with following options:

 * `--bec-address ADDRESS` - source address for BitEtherCoin claim, must be unlocked
 * `--unlock ADDRESS --password PASSWORD_FILE_FOR_ADDRESS` - unlock address

Final command would look like this:

----
echo MYPASSWORD > ./password.txt

./target/release/parity \
    --author 01234567890abcdef0123456789abcdef0123456 \
    --unlock 01234567890abcdef0123456789abcdef0123456 --password password.txt \
    --bec-address 01234567890abcdef0123456789abcdef0123456
----
